### ISSUE TITLE
CURLOPT_FOLLOWLOCATION on servers with safe mode

### ISSUE THREAD

**Issue by aorcsik** [ricardoper/TwitterOAuth#22]
Hi,

I had the following issue on my server, where safe mode is enabled:

> Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in [...]

Is it necessary to have this flag turned on? API endpoints usually don't redirect afaik, but I admit, I didn't check Twitter API spec. Now I commented [this line](https://github.com/ricardoper/TwitterOAuth/blob/v2/src/Common/Curl.php#L61) out, but I don't like to patch third party code, since it will disappear on the next update. If this flag is not necessary for some reason, could you please remove it, or make it user switchable?

Cheers,
Tony

**Comment by ricardoper** [comment]
Hello @aorcsik ,

Thanks for your patience.

cUrl option removed and v2.1.2 released.

Best regards,
Ricardo Pereira.

**Comment by aorcsik** [comment]
Awesome support, thank you! :)

**Comment by ricardoper** [comment]
Hello,

Update to version **v2.1.6** if you want to change cURL default options:
https://github.com/ricardoper/TwitterOAuth/blob/v2/examples/SingleUser_With_cURL_Options.php
https://github.com/ricardoper/TwitterOAuth/blob/v2/examples/ApplicationOnly_With_cURL_Options.php

Best regards,
Ricardo Pereira.
