### ISSUE TITLE
List operations stopped working suddenly

### ISSUE THREAD

**Issue by bunkertor** [ricardoper/TwitterOAuth#23]
Hi,
I switched to using your library after  https://github.com/J7mbo/twitter-api-php became unstable a few months ago but suddenly last week your library stopped working in a similar fashion as the old one had stopped a few months ago. I'm totally confused. Hoping you have some ideas.

We're using your library to make this API call https://dev.twitter.com/rest/reference/post/lists/members/destroy and three different Twitter accounts have three different responses.
Account 1 - works ok
Account 2:
`<b>Fatal error</b>:  Uncaught Twitter Response: [34] Sorry, 
that page does not exist. (TwitterOAuth\Exception\TwitterException)  thrown in 
<b>/home/myserver/public_html/TwitterOAuth-2/src/Auth/AuthAbstract.php</b>
 on line <b>254</b>`

Account 3:
`<b>Fatal error</b>:  Uncaught Twitter Response: [112] You must specify either a list ID or a slug and owner. (TwitterOAuth\Exception\TwitterException)  thrown in <b>/home/myserver/public_html/TwitterOAuth-2/src/Auth/AuthAbstract.php</b> on line <b>254</b>`

How can one script possibly produce 3 different outcomes?
Have you lately experienced any issues with Twitter Lists API?
thanks

**Comment by ricardoper** [comment]
Hello,

Thanks for using this lib.

About your problem:
#1 - List exists and everything its ok.
#2 - At this moment no ideas for this type of error. The url should always exist.
#3 - Its a bad request. You are trying to delete a non existent List. Create it first then delete it.

I will try to investigate in detail this problem as soon as posible.

This accounts have write permissions??? Check If some of accounts have read only permissions.

PHP version? OS? You are using SSL? You are using v2 versión of this lib?

Best regards,
Ricardo Pereira

**Comment by bunkertor** [comment]
Hi Ricardo,
Thank you very much for a quick response.

PHP Version 5.3.29
OS: Kernel Xen 2.6.18-238.9.1.el5xen
SSL: Yes
Version: Yes, the latest version

I'm not sure about write permissions. Sorry, how do I check that? All three accounts were created via my app login page, so I assume they should all be with the same permissions... but I don't know to be honest.

> You are trying to delete a non existent List. Create it first then delete it.
This is the thing. I always test with lists and list members who are verified as existing. The way my app works is it pulls in the list of lists, then when you click on the list, it pulls in the list members. It all happens dynamically. If the twitter account is displayed, it is so for a reason. It means it is a member of a list. And yes, we are talking about public lists. I haven't tested this on private lists yet.

This is what happened to your competitor a few months ago. All list operations with J7mbo Library were working ok. Then I woke up one morning and they all had stopped working. That's why I switched to your library a month ago. And now this has stopped working too. It was still working last week. That's why I don't understand anything.

**Comment by ricardoper** [comment]
Hello,

Which type of auth you are using? App only, single user?

Ok, I will investigate...

Best regards.

**Comment by bunkertor** [comment]
Thanks, Ricardo, I thought I was using the Single User because all operations are carried out using user's own tokens but for some reason the error message is generated by AuthAbstract.php not by SingleUserAuth.php. I'm not sure why.

**Comment by ricardoper** [comment]
Hello @bunkertor ,

I made a few tests and everything is OK.

**Check Permissions:**
* Go To URL https://apps.twitter.com/
* Select Or Create New App
* Select "*Keys and Access Tokens*"
* Verify "*Access Level*" Of "*Application Settings*" And "*Your Access Token*"
* To Create/Update/Delete Lists You Need "*Read and write*" Permissions

After this check use this test file and execute it:

**IMPORTANT:**
* Change credentials to a valid one
* Change *ricard0per* to your test account username
* Using Single User Auth

```php
<?php

date_default_timezone_set('UTC');

require __DIR__ . '/vendor/autoload.php';

use TwitterOAuth\Auth\SingleUserAuth;
use TwitterOAuth\Serializer\ArraySerializer;



$credentials = array(
    'consumer_key' => 'xvz1evFS4wEEPTGEFPHBog',
    'consumer_secret' => 'L8qq9PZyRg6ieKGEKhZolGC0vJWLw8iEJ88DRdyOg',
    'oauth_token' => 'e98c603b55646a6d22249d9b0096e9af29bafcc2',
    'oauth_token_secret' => '07cfdf42835998375e71b46d96b4488a5c659c2f',
);

$auth = new SingleUserAuth($credentials, new ArraySerializer());



/** View Lists */
echo '<b> * View Lists</b><br>';

$params = array(
    'screen_name' => 'ricard0per',
);

$ack = $auth->get('lists/list', $params);

var_dump($ack);

sleep(1);



/** Create List */
echo '<hr><b> * Create List</b><br>';

$listName = 'LIST' . mt_rand(1000, 9999);

$params = array(
    'name' => $listName,
    'mode' => 'public',
    'description' => 'LIST DEMO'
);

$ack = $auth->post('lists/create', $params);

$listSlug = $ack['slug'];

var_dump($ack);

sleep(1);



/** Add Member To List */
echo '<hr><b> * Add Member To List</b><br>';

$params = array(
    'slug' => $listSlug,
    'screen_name' => 'ricard0per',
    'owner_screen_name' => 'ricard0per'
);

$ack = $auth->post('lists/members/create', $params);

var_dump($ack);

sleep(1);



/** View List Members */
echo '<hr><b> * View List Members</b><br>';

$params = array(
    'slug' => $listSlug,
    'owner_screen_name' => 'ricard0per'
);

$ack = $auth->get('lists/members', $params);

var_dump($ack);

sleep(1);



/** Destroy Member From List */
echo '<hr><b> * Destroy Member From List</b><br>';

$params = array(
    'slug' => $listSlug,
    'screen_name' => 'ricard0per',
    'owner_screen_name' => 'ricard0per'
);

$ack = $auth->post('lists/members/destroy', $params);

var_dump($ack);

sleep(1);



/** View List Members */
echo '<hr><b> * View List Members</b><br>';

$params = array(
    'slug' => $listSlug,
    'owner_screen_name' => 'ricard0per'
);

$ack = $auth->get('lists/members', $params);

var_dump($ack);

sleep(1);



/** Delete List */
echo '<hr><b> * Delete List</b><br>';

$params = array(
    'slug' => $listSlug,
    'owner_screen_name' => 'ricard0per'
);

$ack = $auth->post('lists/destroy', $params);

var_dump($ack);

sleep(1);



/** View Lists */
echo '<hr><b> * View Lists</b><br>';

$params = array(
    'screen_name' => 'ricard0per',
);

$ack = $auth->get('lists/list', $params);

var_dump($ack);

```

If everything is correct, you can see that all normal operations are functional.

If you have errors, please give me a feedback to find a solution.

Best regards,
Ricardo Pereira.

**Comment by ricardoper** [comment]
Hello,

Any news about this issue?

Best regards.
