### ISSUE TITLE
No file called autoload

### ISSUE THREAD

**Issue by jamiehutber** [ricardoper/TwitterOAuth#24]
Hey sorry for putting such a silly thing on here, but I've searched the folders and can't find any autoload file. Nor are there are classes that are called `TwitterOAuth\Serializer\ArraySerializer`.

I'm obviously missing something completely.

**Comment by ricardoper** [comment]
Hello @jamiehutber,

In the readme file, you can see some aspects like [PSR-4](http://www.php-fig.org/psr/psr-4/), Namespaced and "The recommended way to install TwitterOAuth is through [Composer](https://getcomposer.org/):".

The autoload file is part of [Composer](https://getcomposer.org/), so you need [Composer](https://getcomposer.org/) installed in your system. [Composer](https://getcomposer.org/) is a dependency manager for PHP and is the best thing that has happened in the PHP World (for me).

Please read [PSR-4](http://www.php-fig.org/psr/psr-4/) but the namespace TwitterOAuth\Serializer\ArraySerializer is translated to this file src/Serializer/ArraySerializer.php and this file exists.

Don't worry, you need to update your PHP knowledges.

Best regards,
Ricardo Pereira.
