### ISSUE TITLE
Enable base64 upload

### ISSUE THREAD

**Issue by tezzutezzu** [ricardoper/TwitterOAuth#26]
I'm not sure if this library is still maintained but I'm currently working on a legacy project where there is the need of uploading images in base64 format as they're generated in javascript using canvas.

As a test I've added the following code in SingleUserAuth.php although Twitter doesn't seem to recognize the media. 

Do you have any suggestion on how this could be accomplished?

Thank you!

`protected function buildMultipartBase64($mimeBoundary, $filebase64)
      {
        
        $data = '--' . $mimeBoundary . static::EOL;
        $data .= 'Content-Disposition: form-data; name="media"; filename="image"' . static::EOL;
        $data .= 'Content-Type: image/jpeg' . static::EOL . static::EOL;
        $data .=  $filebase64. static::EOL;
        $data .= '--' . $mimeBoundary . '--' . static::EOL . static::EOL;

  

        return $data;
    }`

**Comment by ricardoper** [comment]
Hello,

Check this example:
https://github.com/ricardoper/TwitterOAuth/blob/v2/examples/SingleUser_UploadingMedia.php

Has you can see, you must give the filename of the file. You don't need to encode/decode the upload file.

If you have a SVG you need to save it and then upload this SVG file.

At the moment, it's not posible to upload files on-the-fly or streaming.

Best regards,
Ricardo Pereira.

**Comment by tezzutezzu** [comment]
Hi Ricardo, thanks for your quick reply.

I can't save the image on the server that's why I'm sending the image data encoded in base 64 to the script.

**Comment by tezzutezzu** [comment]
Ah, Ricardo I found my problem: 

I need to use "media_data" when I send base64 encoded data.

That solved it for me.

**Comment by tezzutezzu** [comment]
Here's the code I added to SingleUserAuth.php

`public function postMediaBase64($call, $filebase64) {

        $this->resetCallState();

        $this->call = $call;

        $this->method = 'POST';

        $this->withMedia = true;

        $mimeBoundary = sha1($call . microtime());

        $params = array(
            'post' => $this->buildMultipartBase64($mimeBoundary, $filebase64),
            'headers' => $this->buildUploadMediaHeader($mimeBoundary)
            );
        $response = $this->curl->send($this->getUrl(), $params);

        $obj = json_decode($response['body']);

        if (!$obj || !isset($obj->token_type) || $obj->token_type != 'bearer') {
            $this->findExceptions($response);
        }

        $this->headers = $response['headers'];

        $this->withMedia = null;

        unset($call, $filename, $mimeBoundary, $params, $obj);

        return $this->serializer->format($response['body']);
    }

      /**
      * Build a multipart message
      *
      * @param string $mimeBoundary MIME boundary ID
      * @param string $filename File location
      * @return string  Multipart message
      */
      protected function buildMultipartBase64($mimeBoundary, $filebase64)
      {
        
        $type = "image/jpeg";

        $data = '--' . $mimeBoundary . static::EOL;
        $data .= 'Content-Disposition: form-data; name="media_data"; filename="image"' . static::EOL;
        $data .= 'Content-Type: image/jpeg' . static::EOL . static::EOL;
        $data .=  preg_replace('#^data:image/[^;]+;base64,#', '',$filebase64). static::EOL;
        $data .= '--' . $mimeBoundary . '--' . static::EOL . static::EOL;

  

        return $data;
    }`

**Comment by ricardoper** [comment]
Hello @tezzutezzu,

Perfect... Thanks for using this library.

I need some extra time to add some new functionalities:
https://dev.twitter.com/rest/reference/post/media/upload

Best Regards,
Ricardo Pereira.
