### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by steve-calcott** [ricardoper/TwitterOAuth#27]
Not sure if I've missed something here but is there some way of overriding the CURLOPT_CAINFO option in Curl.php (line 64)? Looks like that file doesn't now allow peer connections but using the default from my OS (i.e. commenting out that line) DOES work.

Either that or a new certificate might be worth it - though ideally using non-standard certs might be better be opt-in?

Cheers
S

**Comment by ricardoper** [comment]
Hi @steve-calcott,

Thanks for using this library.

Please, update to **v2.1.6** and check this examples:
https://github.com/ricardoper/TwitterOAuth/blob/v2/examples/SingleUser_With_cURL_Options.php
https://github.com/ricardoper/TwitterOAuth/blob/v2/examples/ApplicationOnly_With_cURL_Options.php

The reason to force CAINFO is that some PHP versions have outdated certificates and cause a lot of connection errors. So in this file we have only the updated certificates that Twitter is using.

I changed this too, now we have [Mozilla CA Certificates](https://curl.haxx.se/docs/caextract.html) and I hope this solve your problem without add any line of code. If not, try the examples mentioned.

Best regards,
Ricardo Pereira.

**Comment by steve-calcott** [comment]
Great - thanks for the example @ricardoper and doing this so quickly.

Best, Steve
